pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git 'https://github.com/sakshimohinia/CICDDemo.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t springboot-app .'
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -p 8080:8080 springboot-app'
            }
        }
    }
}